# Generated by Django 4.1.7 on 2023-07-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.internshipprograms'),
        ),
    ]
